openapi: 3.1.0
info:
  title: Pledge Pilot API
  description: REST API of Pledge Pilot
  version: "v1.0"
servers:
  - url: http://localhost:8080
paths:
  /user:
    get:
      operationId: get-user
      description: gets user
      parameters:
        - name: name
          in: query
          required: true
          example: Aaryan
          schema:
            type: string
      responses:
        "200":
          description: user found
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/user"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    user:
      type: object
      properties:
        name:
          type: string
          examples:
            - "Aaryan"
        lastName:
          type: string
          examples:
            - "Praveen"
        amountDonated:
          type: number
          examples:
            - 1000
        hasProject:
          type: boolean
          examples:
            - true
        projects:
          type: array
          examples:
            - ["123", "234", "456"]
        schedule:
          $ref: "#/components/schemas/Schedule"
    Schedule:
      type: object
      properties:
        start-time:
          type: string
          format: date-time
          examples:
            - "2023-11-12T13:14:15Z"
        end-time:
          type: string
          format: date-time
          examples:
            - "2023-11-12T13:14:15Z"
    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
          examples:
            - UserNotFound
        message:
          type: string
          description: Error message
          examples:
            - User not Found
